[tool.black]
line-length = 119

[tool.pytest.ini_options]
log_level = "INFO"
log_format = "%(asctime)s.%(msecs)03.0f %(levelname)-10s %(name)-50s %(funcName)35s %(lineno)-4s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"